# Matemática e Estatística
## Prof. Ujeverson Tavares

## Soma de matrizes

### Matriz linha

In [3]:
import numpy as np


In [15]:
#escrevendo uma matriz 2x2
m1 = np.array([[1, -3, 5],[-4, -8, 12], [-5, 8, 2]], dtype=int)
m1

array([[ 1, -3,  5],
       [-4, -8, 12],
       [-5,  8,  2]])

In [5]:
#.shape mostra a dimensão da matriz
m1.shape

(2, 2)

In [6]:
#escrevendo uma matriz com números no intervalo [0,1)
B = np.random.rand(4, 3)
B

array([[0.68845743, 0.00865416, 0.02629938],
       [0.22317224, 0.69391249, 0.61320176],
       [0.18913936, 0.94563275, 0.63494707],
       [0.30160008, 0.8860796 , 0.07612319]])

In [7]:
#matriz nula
C = np.zeros((3,3))
C

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [8]:
#criar uma matriz diagonal
D = np.diag([-1,1,8])
D

array([[-1,  0,  0],
       [ 0,  1,  0],
       [ 0,  0,  8]])

In [9]:
#criar uma matriz identidade
I2 = np.identity(3) #matriz identidade de ordem 3
I2
I8 = np.identity(8) #matriz identidade de ordem 8
I8

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]])

In [16]:
#localizar um elemento na matriz
m1

array([[ 1, -3,  5],
       [-4, -8, 12],
       [-5,  8,  2]])

In [11]:
m1[0,1] 

-3

In [12]:
#ou
m1[0][1]

-3

In [18]:
#ou
m1[-2][-3]

-4

In [19]:
#ou
m1[-2,-2]

-8

In [20]:
#imprimir os elementos de uma coluna
m1[:,1]

array([-3, -8,  8])