In [9]:
import numpy as np

## Tipo de matrizes

## Matriz linha

In [10]:
A = np.array([[1, 2, -3]])
print("A=",A,"\nDimensão:",np.shape(A))

A= [[ 1  2 -3]] 
Dimensão: (1, 3)


## Matriz coluna

In [11]:
B = np.array([[1], [2], [-3]])
print("B=",B,"\nDimensão:",np.shape(B))

A= [[ 1]
 [ 2]
 [-3]] 
Dimensão: (3, 1)


## Matriz quadrada

In [15]:
C = np.array([[1.2, -3, 5],[-4, -8, 12], [-5, 8, 2]], dtype = int)
print("C=\n",C,"\nDimensão:",np.shape(C))

C=
 [[ 1 -3  5]
 [-4 -8 12]
 [-5  8  2]] 
Dimensão: (3, 3)


In [16]:
D= np.array([[1, -3, 5],[-4, -8, 12], [-5, 8, 2]])
D

array([[ 1, -3,  5],
       [-4, -8, 12],
       [-5,  8,  2]])

In [17]:
D[2][0]

-5

In [18]:
D[2,0]

-5

In [19]:
a = int(input("Digite o valor que quer mudar:"))

Digite o valor que quer mudar:5


In [20]:
a

5

In [21]:
D[2,0] = a
D

array([[ 1, -3,  5],
       [-4, -8, 12],
       [ 5,  8,  2]])

In [23]:
C = np.array([[4],[7],[3],[4]])
C

array([[4],
       [7],
       [3],
       [4]])

In [24]:
a = C[0,0]
c = C[1,0]
s = C[2,0]
t = C[3,0]

In [25]:
muda_a = int(input("Digite o novo valor da porção de arroz:"))
C[0,0] = muda_a

Digite o novo valor da porção de arroz:3


In [26]:
C

array([[3],
       [7],
       [3],
       [4]])

In [27]:
muda_c = int(input("Digite o novo valor da porção de arroz:"))
C[1,0] = muda_c

Digite o novo valor da porção de arroz:4


In [28]:
C

array([[3],
       [4],
       [3],
       [4]])

In [29]:
P = np.array([[2, 2, 1, 1],[1, 2, 1, 1],[2, 2, 0,3]])
print(P)

[[2 2 1 1]
 [1 2 1 1]
 [2 2 0 3]]


In [30]:
C = np.array([[4],[7],[3],[4]])
C

array([[4],
       [7],
       [3],
       [4]])

In [31]:
P_C = np.dot(P,C)
P_C

array([[29],
       [25],
       [34]])

In [32]:
print("Prato 1 vale R$",P_C[0,0])
print("Prato 2 vale R$",P_C[1,0])
print("Prato 3 vale R$",P_C[2,0])

Prato 1 vale R$ 29
Prato 2 vale R$ 25
Prato 3 vale R$ 34
