In [1]:
import numpy as np

## Matriz linha

In [27]:
A = np.array([[1, -3, 6, 8]])
print("A=", A, "\nOrdem:",np.shape(A))

A= [[ 1 -3  6  8]] 
Ordem: (1, 4)


## Matriz coluna

In [8]:
B = np.array([[1],[-3],[6],[8]])
print("B=", B, "\nOrdem:",np.shape(B))

B= [[ 1]
 [-3]
 [ 6]
 [ 8]] 
Ordem: (4, 1)


## Matriz quadrada

In [36]:
C = np.array([[1, 0.1, -2.3, 0.2],[-3, 0, 3 , 4],[6, -7, 81, 2],[8, 7, 6 ,5]])
print("C=\n", C, "\nOrdem:",np.shape(C))

C=
 [[ 1.   0.1 -2.3  0.2]
 [-3.   0.   3.   4. ]
 [ 6.  -7.  81.   2. ]
 [ 8.   7.   6.   5. ]] 
Ordem: (4, 4)


## Matriz nula

In [17]:
 D = np.zeros((2,4))
 D

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

## Matriz diagonal

In [18]:
E = np.diag([1, 0, -3])
E

array([[ 1,  0,  0],
       [ 0,  0,  0],
       [ 0,  0, -3]])

## Matriz identidade

In [19]:
I = np.diag([1,1,1,1])
I

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [20]:
I3 = np.identity(3)
I3

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Localizar um elemento na matriz

In [37]:
print(C)

[[ 1.   0.1 -2.3  0.2]
 [-3.   0.   3.   4. ]
 [ 6.  -7.  81.   2. ]
 [ 8.   7.   6.   5. ]]


In [38]:
C[0,1]

0.1

In [39]:
C[2,2]

81.0

In [40]:
C[-1, -2]

6.0

In [42]:
C[-4, -3]

0.1